# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
config.vm.box = "centos/stream8"
config.ssh.insert_key = false

config.vm.define "server" do |server|
  server.vm.hostname = "server.loc"
  server.vm.network "private_network", ip: "192.168.56.10"

  server.vm.provider "virtualbox" do |vb|
    vb.name = "server_loc_vpn"
    vb.memory = 2048
    vb.cpus = 1
  end
end

config.vm.define "client" do |client|
  client.vm.hostname = "client.loc"
  client.vm.network "private_network", ip: "192.168.56.20"    
  
  client.vm.provider "virtualbox" do |vb|
        vb.name = "client_loc_vpn"
        vb.memory = 2048
        vb.cpus = 1
      end
  
  client.vm.provision "ansible" do |ansible|
      ansible.playbook = "ras.yml"
      ansible.become = "true"
      ansible.limit = "all"
    end
 
 
  end

end
