# -*- mode: ruby -*-
# vim: set ft=ruby :

MACHINES = {
    :zabserv => {
        :box_name => "ubuntu/focal64",
        :ip_addr => '192.168.11.170',
        :cpus => 2,
        :memory => 2048,
    },
    :agent1 => {
        :box_name => "ubuntu/focal64",
        :ip_addr => '192.168.11.171',
        :cpus => 1,
        :memory => 1024,
    },
  }

Vagrant.configure("2") do |config|
  MACHINES.each do |boxname, boxconfig|
      config.vm.define boxname do |box|
          box.vm.box = boxconfig[:box_name]
          box.vm.host_name = boxname.to_s 
          box.vm.network "private_network", ip: boxconfig[:ip_addr]
          box.vm.provider :virtualbox do |vb|
            vb.memory = boxconfig[:memory]
            vb.cpus = boxconfig[:cpus] 	        
          end
        end
  end
end
