# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure(2) do |config|
    
  config.ssh.insert_key = false
  config.vm.provider "virtualbox" do |v|
    v.memory = 1024
    v.cpus = 1
  end

  config.vm.define "vm1" do |vm1|
    vm1.vm.box = "centos/7"
    vm1.vm.network "private_network", ip: "192.168.11.155"
  end
  config.vm.define "vm2" do |vm2|
    vm2.vm.box = "ubuntu/focal64"
    vm2.vm.network "private_network", ip: "192.168.11.156"
    vm2.vm.hostname = "ubuntu-server"
    vm2.vm.provision "ansible" do |ansible|
      ansible.playbook = "nginx_install.yml"
      ansible.become = "true"
      ansible.limit = "all"
    end
  end  
   
end