# -*- mode: ruby -*-
# vim: set ft=ruby :

servers = {
    :systemd => {
        :box_name => "centos/7",
        :cpus => 2,
        :memory => 1024,
    },
}

Vagrant.configure("2") do |config|
    config.vm.box_version = "1804.02"

    
    # config.vm.synced_folder ".", "/vagrant", disabled: True
    
    servers.each do |boxname, boxconfig|
      config.vm.define boxname do |box|
          box.vm.box = boxconfig[:box_name]
          box.vm.host_name = boxname.to_s 
         
          box.vm.network "private_network", ip: "192.168.11.120"
         
          box.vm.provider :virtualbox do |vb|
            vb.memory = boxconfig[:memory]
            vb.cpus = boxconfig[:cpus] 	        
          end

          box.vm.provision "shell", path: "task1-watchlog-timer.sh"          
          box.vm.provision "shell", path: "task2-spawn-fcgi-service.sh"          
          box.vm.provision "shell", path: "task3-httpd.sh"          


      end
  end
end